# Generated by Django 3.2.2 on 2021-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
