# Generated by Django 3.2.2 on 2021-05-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_1', '0002_auto_20210506_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='challenge_1.pet'),
        ),
    ]
